version: '3.7'
services:
  app:
    build: sandbox-service-rest
    ports:
      - ${REST_APPLICATION_EXT_PORT}:${REST_APPLICATION_INT_PORT}
    depends_on:
      - mongodb
    environment:
      SERVER_PORT: ${REST_APPLICATION_INT_PORT}
      MONGODB_USER: ${MONGODB_USER}
      MONGODB_PASSWORD: ${MONGODB_PASSWORD}
      MONGODB_HOST: ${MONGODB_HOST}
      MONGODB_PORT: ${MONGODB_PORT}
      MONGODB_DATABASE: ${MONGODB_DATABASE}
  mongodb:
    image: ${MONGO_IMAGE}
    hostname: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
    ports:
      - ${MONGODB_PORT}:${MONGODB_INT_PORT}
